kind: Deployment
apiVersion: apps/v1
metadata:
  name: django
  namespace: ocs4-tools
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      name: django
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: 'quay.io/cerginba/rlocker-django'
          imagePullPolicy: "Always"
          envFrom:
            - configMapRef:
                name: django-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}